# Generated by Django 4.2.30 on 2026-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="料理名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meat", "お肉メイン"),
                            ("fish", "お魚メイン"),
                            ("other", "野菜・その他・定番"),
                        ],
                        default="meat",
                        max_length=20,
                        verbose_name="ジャンル",
                    ),
                ),
                (
                    "last_cooked_date",
                    models.DateField(blank=True, null=True, verbose_name="最後に作った日"),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ・ポイント")),
            ],
        ),
    ]
