# Generated by Django 4.2.30 on 2026-09-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dish",
            name="last_cooked_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="memo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dish", name="name", field=models.CharField(max_length=100),
        ),
    ]
